In [ ]:
# A. Condicionales (if, elif, else)

In [4]:
# 1.Comparar dos números , num1 , num2
num1 = 30
num2 = 20
if num1==num2:
    print('los numeros son iguales')
elif num1>num2:
    print('num1 es mayor que num2')
    print(f"{num1} es mayor que {num2}")# f"{variable} lo que sea" f""
else:
    print('num1 es menor que num2')

num1 es mayor que num2
30 es mayor que 20


In [8]:
# 2.Clasificación de edades
""" 
Escribe un programa que clasifique a una persona en función de su edad ingresada.

-Menor de 12 años: “Niño”.
-Entre 12 y 17 años: “Adolescente”.
-Entre 18 y 64 años: “Adulto”.
-65 años o más: “Adulto mayor”.
"""
edad = int(input('ingresa tu edad'))
if edad<12:
    print('niño') # es niño porque su edad es : 
elif 12<=edad<=17:
    print('adolescente')
elif 18<=edad<=64:
    print('adulto')
else:
    print('adulto mayor')

ingresa tu edad30
adulto


In [12]:
# 3.Determinar si un número es positivo, negativo o cero
numero = int(input('ingresa el numero'))
if numero >0:
    print('el numero es positivo')
elif numero<0:
    print('el numero es negativo')
else:
    print('es igual a cero')

ingresa el numero0
es igual a cero


In [20]:
# 4.Calculadora de propinas
"""Escribe un programa que calcule el monto de una propina dependiendo de la calidad del servicio recibida.

	•	Servicio “excelente”: 20% de propina. if
	•	Servicio “bueno”: 15% de propina.elif
	•	Servicio “regular”: 10% de propina.elif
	•	Servicio “malo”: 5% de propina.elif
    El programa debe pedir el monto de la factura y el tipo de servicio. 
 """
#tener 2 variables : el tipo de servicio , la propina final
monto = float(input('ingresa el monto de la factura'))
servicio = input('calidad del servicio(excelente, bueno , regular , malo)') 
#sino decimos el tipo de input python asume que es tipo texto o string
if servicio == "excelente":
    porcentaje=0.20
    print(monto*porcentaje)
elif servicio=="bueno":
    porcentaje=0.15
elif servicio=="regular":
    porcentaje = 0.10
elif servicio=="malo":
    porcentaje= 0.05
else:
    porcentaje=0
    print('escribiste algo incorrecto')
    
if porcentaje>0:
    propina = monto * porcentaje
    print(propina)



ingresa el monto de la factura500
calidad del servicio(excelente, bueno , regular , malo)121
escribiste algo incorrecto


In [ ]:
# 5.Verificar si el numero es Par o Impar

In [6]:
# 6.Calificación de examen
"""
Escribe un programa que le pida al usuario su calificación (entre 0 y 100) y le muestre la letra correspondiente según la siguiente escala:

	•	90-100: A
	•	80-89: B
	•	70-79: C
	•	60-69: D
	•	Menos de 60: F
"""

In [ ]:
# 7.Clasificación de temperaturas
"""
Escribe un programa que determine la categoría de una temperatura en grados Celsius:

	•	Menos de 0°C: “Congelación”.
	•	0°C a 10°C: “Frío”.
	•	11°C a 20°C: “Templado”.
	•	21°C a 30°C: “Cálido”.
	•	Más de 30°C: “Calor”.
"""


In [ ]:
# 8.Clasificación de distribución de datos
"""
Escribe un programa que clasifique un conjunto de datos como sesgado hacia la izquierda, hacia la derecha o 
simétrico. La clasificación se basa en la diferencia entre la media y la mediana de los datos:

	•	Si la media es mayor que la mediana, los datos están sesgados a la derecha.
	•	Si la media es menor que la mediana, los datos están sesgados a la izquierda.
	•	Si la media es igual a la mediana, los datos son simétricos.
"""

In [ ]:
# 9.Análisis de regresión simple
"""
Dado un conjunto de datos con valores de x y y, calcula la pendiente y la 
intersección de la recta de regresión lineal (y = mx + b). Luego, clasifica la relación:

	•	Si la pendiente es positiva, imprime “Relación positiva”.
	•	Si la pendiente es negativa, imprime “Relación negativa”.
	•	Si la pendiente es cercana a cero (por ejemplo, entre -0.1 y 0.1), 
        imprime “No hay correlación significativa”.
"""



In [22]:
# 11. Clasificación de valores Z
"""
Escribe un programa que calcule el valor Z de un conjunto de datos dado y lo clasifique según los siguientes criterios:

	•	Entre -1 y 1: Valor normal.
	•	Mayor que 1: Valor alto.
	•	Menor que -1: Valor bajo.
    # Conjunto de datos y valor a clasificar
datos = np.array([10, 12, 14, 15, 16, 18, 19, 20, 21])
valor = 15
"""
#valor_z = (valor - media )/ std

import numpy as np # 'as' es un alias y le ponemos un nombre x a la libreria 

datos = np.array([10, 12, 14, 15, 16, 18, 19, 20, 21])
valor = 15

media = np.mean(datos) # np.mean es para calcular la media 
desv_standar = np.std(datos)

valor_z = (valor-media) / desv_standar
print(valor_z)
if -1<= valor_z<=1:
    print('valor normal')
elif valor_z > 1:
    print('el valor es alto')
else:
    print('el valor es bajo')

-0.3165444689164591
valor normal


In [ ]:
# 12. Resolver ecuaciones cuadraticas 
"""
Escribe un programa que resuelva ecuaciones cuadráticas de la forma  ax^2 + bx + c = 0 , y clasifique las soluciones:

	•	Si el discriminante es positivo, imprime “Dos soluciones reales”.
	•	Si el discriminante es cero, imprime “Una solución real”.
	•	Si el discriminante es negativo, imprime “Soluciones complejas”.

La fórmula cuadrática es:
"""

In [25]:
#13 
"""Ejercicio 1: Verificación de Edad y Membresía (Básico)

Problema: Escribe un programa que pida al usuario su edad y si es miembro de un club
(sí o no). El programa debe imprimir un mensaje indicando si la persona es elegible 
para acceder a un evento especial. Las condiciones para ser elegible son:
	•	La persona debe tener al menos 18 años.
	•	La persona debe ser miembro del club.
"""
# and condi1 condi2 ambas deben cumplirse
# or cond1 , condi2 , solo debe cumplirse una de ellas
edad = int(input('Ingresa tu edad '))
membresia = input('eres miembro ? si/no ')

if edad >= 18 and membresia == 'si':
    print('puedes ingresar al evento especial')

else:
    print('no puedes ingresar al evento especial')





Ingresa tu edad17
eres miembro ? si/nono
no puedes ingresar al evento especial


In [26]:
#14
'''Ejercicio 2: Descuento en Compras (Intermedio)

Problema: Crea un programa que calcule el descuento en una compra. El programa debe preguntar el valor total 
de la compra y si el cliente es miembro VIP (sí o no). Las reglas de descuento son:
	•	Si el valor de la compra es mayor a $100 y el cliente es miembro VIP, el descuento es del 20%.
	•	Si el valor de la compra es mayor a $100 pero el cliente no es miembro VIP, el descuento es del 10%.
	•	En cualquier otro caso, no hay descuento.
'''

valor_de_compra = float(input('cual es el valor de la compra '))
vip= input('eres vip , si/no')

if valor_de_compra >100 and vip=='si ':
    descuento = valor_de_compra * 0.20

elif valor_de_compra >100 and vip=='no ':
    descuento = valor_de_compra * 0.1

else:
    descuento = 0
    
monto_final = valor_de_compra - descuento
print(descuento)
print(monto_final)
    
    

cual es el valor de la compra120
eres vip , si/nosi
24.0
96.0


In [43]:
import numpy as np

#como crear una array o lista o vector a = np.array([])

a = np.array([1,2,3,4,5,6])#vector unidimensional 
b = np.array([[1,2,3],[3,4,5]])
# 123
# 456
print(a)
print(b)

#matriz de ceros
zeros = np.zeros(5)
print(zeros)

#matriz de unos 
unos = np.ones((2,3))
print(unos)

vector1 = np.array([1,2,3]) # n x m
vector2 = np.array([4,5,6]) # n x m

#concatenado n x 2*m
concatenacion_de_vectores = np.concatenate((vector1,vector2))
print(concatenacion_de_vectores)

#apilado  x m
apilado = np.vstack((vector1,vector2))
print(apilado)









[1 2 3 4 5 6]
[[1 2 3]
 [3 4 5]]
[0. 0. 0. 0. 0.]
[[1. 1. 1.]
 [1. 1. 1.]]
[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]


In [42]:
#matriz columna 
vcolumna = np.array([[1] , [2] , [3]])

print(vcolumna)

[[1]
 [2]
 [3]]


In [52]:
#operaciones aritmeticas
vector1 = np.array([1,2,3,4])

#suma de un numero a cada elemento del vector
#print(vector1 +5)

#multiplicar un numero a cada elemento del vector
#print(vector1 * 2)

#potencia vector ** potencia
#print(vector1 ** 2)

#seno asume que esta en radianes
#print(np.sin(vector1))

#coseno
#print(np.cos(vector1))

#logaritmo 
#print(np.log(vector1))

#raiz cuadrada
print(np.sqrt(vector1))

[1.         1.41421356 1.73205081 2.        ]


In [54]:
# producto de matrices 

A = np.array([[1 , 2],[3 , 4]])
B = np.array([[5 , 6],[7 , 8]])

C = np.dot(A,B)
print(C)

[[19 22]
 [43 50]]


In [85]:
#Operaciones estadisticas

vector1 = np.array([1,2,3,4,5])
# np.mean (MEDIA)
media = np.mean(vector1)
print('MEDIA = ',media)

# np.median (MEDIANA)
mediana = np.median(vector1)
print('MEDIANA = ',mediana)

# np.std (DESVIACION ESTANDAR)
desv_std = np.std(vector1)
print(f"DESVIACION ESTANDAR = {desv_std:.3f}")

# np.var (VARIANZA)
varianza = np.var(vector1)
print('VARIANZA = ', varianza )

#el maximo y el minimo del vector np.max np.min
maximo = np.max(vector1)
minimo = np.min(vector1)

print(f"el maximo es {maximo} y el minimo es {minimo}")

# np.percentile() (PERCENTIL)
percentil_25 = np.percentile(vector1,25)
percentil_75 = np.percentile(vector1,75)

print(f"percentil 25 = {percentil_25} y el percentil 75 = {percentil_75}")

# np.quantile() ( cuartiles)
cuartil_25 = np.quantile(vector1,0.25)
cuartil_75 = np.quantile(vector1,0.75)

print(f"cuartil 1 = {cuartil_25} y el cuartil 3 {cuartil_75} ")

MEDIA =  3.0
MEDIANA =  3.0
DESVIACION ESTANDAR = 1.414
VARIANZA =  1.4142135623730951
el maximo es 5 y el minimo es 1
percentil 25 = 2.0 y el percentil 75 = 4.0
cuartil 1 = 2.0 y el cuartil 3 4.0 


In [74]:
#coeficiente de correlacion 
vector1 = np.array([1,2,3,4,5])
vector2 = np.array([5,4,3,2,1])

correlacion = np.corrcoef(vector1,vector2)
#print(correlacion)

#matriz covarianza np.cov
covarianza = np.cov(vector1 , vector2)
print(covarianza)

[[ 2.5 -2.5]
 [-2.5  2.5]]


In [86]:
#15
import numpy as np
# media , mediana , varianza , desviacion estandar , calificacion minima , calificacion maxima
# Datos de calificaciones de 20 estudiantes en 4 exámenes
calificaciones = np.array([
    #n1  n2  n3  n4
    [85, 90, 78, 92],
    [88, 76, 85, 91],
    [92, 89, 93, 85],
    [67, 72, 70, 65],
    [80, 78, 88, 84],
    [85, 91, 82, 89],
    [90, 88, 76, 95],
    [78, 74, 70, 80],
    [81, 85, 77, 79],
    [73, 70, 68, 72],
    [95, 94, 92, 96],
    [60, 62, 65, 68],
    [88, 87, 85, 90],
    [83, 80, 85, 84],
    [77, 76, 74, 75],
    [70, 72, 78, 79],
    [88, 90, 91, 89],
    [85, 83, 82, 86],
    [76, 78, 79, 80],
    [92, 90, 88, 94]
])

#media 0 es por columna y 1 es por fila
media = np.mean(calificaciones , axis=0)
print('la media es ',media)

#mediana
mediana = np.median(calificaciones , axis=0)
print('la mediana es ',mediana)

#varianza
varianza = np.var(calificaciones , axis =0)
print('la varianza es ',varianza)

#desviacion estandar 
desviacion = np.std(calificaciones, axis=0)
print('la desviacion estandar es ',desviacion)

#calificacion maxima 
maxima = np.max(calificaciones , axis =0)
print(maxima)

#calificacion minima
minima = np.min(calificaciones , axis =0)
print(minima)

la media es  [81.65 81.25 80.3  83.65]
la mediana es  [84.  81.5 80.5 84.5]
la varianza es  [79.1275 72.0875 64.11   74.5275]
la desviacion estandar es  [8.89536396 8.4904358  8.00687205 8.63293114]
96
[60 62 65 65]


In [ ]:
import numpy as np
# Datos de calificaciones de 20 estudiantes en 3 materias (Matemáticas, Física, Química)
calificaciones = np.array([
    [88, 92, 79],
    [76, 85, 80],
    [89, 90, 87],
    [70, 78, 82],
    [85, 88, 76],
    [92, 94, 89],
    [75, 80, 85],
    [88, 89, 90],
    [80, 83, 78],
    [84, 86, 82],
    [77, 80, 79],
    [90, 92, 88],
    [83, 85, 84],
    [78, 79, 82],
    [85, 88, 86],
    [89, 91, 87],
    [92, 93, 91],
    [76, 78, 80],
    [85, 87, 82],
    [90, 94, 88]
])
